// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zxxurokvftaomuwjjdhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eHVyb2t2ZnRhb211d2pqZGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzEwNjAsImV4cCI6MjA3MTkwNzA2MH0.F3tRYHMIL_p9JD3f_sYiHi4aZcFYkWGECSUaXyG2tR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);